### ISSUE TITLE
The shop page toggle buttons are not constrained to the toolbar:

### ISSUE THREAD

**Issue by danielpgp1012** [favo-sdp/Favo#268] opened 2020-05-30 13:15 UTC
![image](https://user-images.githubusercontent.com/24901509/83329202-72976d80-a288-11ea-9084-273bae514ef5.png)

**Comment by mikanikos** [comment] 2020-05-30 13:16
Duplicate of #248

**Closed by mikanikos** 2020-05-30 13:16 UTC
Labels: bug
